public class YSEALI_UserData
{
  public String fname{ get; set; }
  public String lname{ get; set; }
  public String birthyear{ get; set; }
  //09/26/14 make changes to match field name in MailChimp
  //CitizenShip
  public String citizen{ get; set; }
  public String residence{ get; set; }
  //04/28/15
    public String cities{ get; set; }
  //09/26/14 make changes to match field name in MailChimp
  //Solving Regional Issues
  public String regional{ get; set; }
  //Protect the environment
  public String environ{ get; set; }
  //Increase community prosperity  
  public String prosper{ get; set; }
  //Educate my generation
  public String educate{ get; set; }
  //Have participated ...
  public String priorpar{ get; set; }
}